### ISSUE TITLE
Timeline of changes in translation

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2181]
Depends on:
- [x] #2203 instance._state_updated not correct
- [x] #2207 Implement history model
- [x] #2208 Write specification for history feature
- [x] #2209 convert existing code to history model
- [x] #2210 Implement initial UI for unit history
- [x] #2237 Fix incorrect statistics with Submission
- [x] #2277 Style history
- [x] #2283 Implement UI for unit timeline
- [x] #2356 No indication of who translated the current unit
- [x] #2359 Timeline slide in and slide out is inconsistent
- [x] #2366 Timeline behaves inconsistently with no data and should simply toggle
- [x] #2399 Ensure submission data is always available per-unit

_See also:_
- https://bugzilla.mozilla.org/show_bug.cgi?id=627908

Scrumdo sotry 153 Bug 627908 - History of changes in translations

Story Creator: dwayne

Communities with several translators it would be useful to have a history of changes to the translations. This would make transparent the changes people made.

https://bugzilla.mozilla.org/show_bug.cgi?id=627908
## Needs clarification

The commenter on the bug wanted to track changes across a project or a language. I'm not sure if this is history of the changes to an arbitrary text that appears or repeats across multiple instance. Or if they mean the specific translation of one sentence.
## Comment

We should implement this apart from the main Pootle data store. This is then simply a log of changes that can be retrieved when needed. The log would store the diff and the person who made the change. Thus you would see changes, who made them etc.

This opens up a whole other set of stories about wanting to revert. Wanting to back out changes by spammers or bad people or rolling back changes by someone. The log might provide the best way to roll back without burdening Pootle with version tracking.
