### ISSUE TITLE
Context information can be confusing

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2183]
Depends on:
- [x] #2188 Add the ability to shrink the amount of context rows
- [x] #2189 Add the ability to show/hide context rows
- [x] #2293 'Show more context rows' pointer is incorrect
- [x] #2308 Hide context information for checks
- [x] #2309 Expand and shrink context one unit at a time
- [x] #2310 Replace More/Less in context expansion with icons

When someone browses some subset in Pootle we add context rows.  But this can be confusing as it is not very clear that this is in fact context information. A user can expand but can't hide or shrink this information.  There are many cases in which this info is not needed but not way of hiding it.  We also would prefer people to have context when they need it and it doesn't seem like something people would discover.

The bigger issue then giving people context is that at the moment it gets in the way and is confusing which I think is worse then not providing it.
## Some ideas

1) Better styling to show that it is context
2) Enable shrinking and hiding to make it go away.
3) Eliminate context by default in certain types of queries e.g. quality checks
4) Hover to show context.  Hover over the show context button and it will show it for that unit. But hide it subsequently.
