### ISSUE TITLE
New overview summary page implementation issues

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2218]
Depends on:
* [x] #1625 Warn users about actions that could take long
* [ ] #2219 Use locale aware number throughout Pootle
* [x] #2220 Overview page expanded view stats do not update when drilling down
* [x] #2221 Expanded overview page translation states should not be present if they are zero
* [x] #2222 No notification of progress when expanding checks on TP overview page
* [x] #2223 Overview number columns header must be right aligned
* [x] #2224 Overview page column headers should remember their sort order
* [x] #2225 Make overview page progress bars proportional
* [x] #2226 Add progress bar to overview header
* [x] #2227 Evaluate moving progress bars under file/dir names in overview tab
* [x] #2228 Clicking on an overview directory or file should leave you in overview mode
* [x] #2229 When a directory has no files it has no progress bar
* [x] #2230 Expanded overview table reading issues
* [x] #2231 Once we have the expanded view statistics we should use them
* [x] #2232 No indication of items that have suggestions
* [x] #2234 When translating the overview tab should take you back to where you were
* [x] #2242 Add link to parent directory
* [ ] #2243 Drilling down into directories in overview page causes file list columns to change size
* [x] #2252 Upload file, Upload to dropbox doesn't filter
* [x] #2276 Overview page summary title shouldn't include language and project codes
* [x] #2289 Make Pootle progress bar clickable
* [x] #2305 Overview check row should be clickable
* [x] #2306 Expanded overview 'Untranslated' points to incomplete
* [x] #2307 Entering a folder with no translations causes backtrace in progressbar.py
* [x] #2345 Strange rendering on overview progressbar
* [x] #2362 Files and directories with "0 words needing attention" mask those that do need work
* [x] #2447 Use a table for rendering the checks

*Created [attachment 840](http://bugs.locamotion.org/attachment.cgi?id=840)*

Expanded overview

This is a tracker for all issues noted with the new implementation of the overview summary page.

The implementation was based on these mockups http://translate.sourceforge.net/wiki/developers/pootle/overview_page_design_-_mockups

This tracker will note all bugs noted in the annotated images that I'll upload.  But the bugs for each issue will be reported separately so that we can prioritise them individually.

**Comment by dwaynebailey** [comment]
Who know which version of the overview this was tracking.  Lets assume the overview as we know it now on ``core`` is completely unrelated to this list.
