### ISSUE TITLE
Mozilla Pootle 2012.1 (Mar-Aug)

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2244]
Depends on:
* [x] #1491 Batch commit pending work from CLI
* [x] #1785 Textarea(s) not disabled with no permissions
* [x] #1877 svn add && svn ci for locales added by frontend
* [x] #2128 Obfuscate email addresses
* [x] #2134 Add a Terms of Use page
* [x] #2142 [TRACKER] Mozilla Firefox on Pootle
* [x] #2168 Report errors and improvements in source text
* [x] #2169 Notify translators about new work and information
* [x] #2170 Easy update of Server/Project/Language descriptions and info
* [x] #2180 Adding multiple notes (comments) as a timeline in units
* [x] #2181 [TRACKER] Timeline of changes in translation
* [x] #2255 Add new files that appear in version control
* [ ] #2278 API for aggregated contributors metrics
* [x] #2279 In Quick Translation, offer option to only display untranslated strings and fuzzily translated strings
* [ ] #2280 Verbatim needs to use an indexing engine
* [ ] #2281 API to get strings still in need of translation
* [ ] #2282 Precommit hook to catch formatting syntax error in translations
* [x] #2314 Separate version control checkouts
* [ ] #2340 [TRACKER] Deploy Pootle at Mozilla
* [ ] #2409 Users without the 'can admin a project' permission should be able to update files from templates
* [x] #2410 Check if Mozilla bug 641324 (Extracted comments are not always displayed) exists in Pootle 2.2
* [x] #2411 Examine Mozilla bug 660119 (Verbatim breaks python variables when it saves files)
* [x] #2412 'hassuggestion' filter returns zero results

Tracking the Translate Mozilla engagement bugs for 2012 Mar-Aug

Use this as the tracker bug for all bugs related to the engagement.  Makes finding and tracking their status much easier.  Each subbug should point the the Mozilla bugzilla related bug.

Only Mozilla issues should be linked to this bug.  If you need to create sub-bugs to implement the feature then link those to the feature bug not to this bug.

**Comment by unho** [comment]
@dwaynebailey Can this be closed?

**Comment by dwaynebailey** [comment]
@unho yip closing these aged trackers
