### ISSUE TITLE
Add new files that appear in version control

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2255]
Depends on:
- [x] #2275 Investigate around VCS options
- [x] #2300 Identify use cases for VCS interaction in pootle
- [x] #2314 Separate version control checkouts
- [x] #2315 Document how separate VCS checkouts work

_See also:_
- https://bugzilla.mozilla.org/show_bug.cgi?id=566748

Pootle is unable to aromatically discover new files that have been added in version control.

When doing an update from version control any files that have been removed should be removed from the project and any new files should be added to the project.

From scrumdo story #158
