### ISSUE TITLE
API for aggregated contributors metrics

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2278]
Depends on:
* [ ] #2873 Expand the API specs
* [ ] #2874 [TRACKER] Add basic API to Pootle
* [x] #2960 API: Add statistics to UserResource

*See also:*
 * https://bugzilla.mozilla.org/show_bug.cgi?id=679403

"Mozilla Phonebook team needs to incorporate contributor metrics into phonebook (i.e. mozillians.org) profiles.

# Mozilla needs

Access to the following information:

* Contributor e-mail address
* Number of translated strings contributed and accepted 
* Number of products localized
* Any other useful statistics

# Generic needs

There is a general need to monitor the state of a Pootle server.  These statistics could include such calculations as:

* Speed of translations per language
* Top contributors
* Translation completion over time

# Comments

* Would it be worth treating statistics as a separate process.  The data is updated outside of Pootle the translation tool.
* We need to approach this in a way that allows new types of statistics to be added.
* We should think about this being useful for providing info that could be used in badges."

**Comment by dwaynebailey** [comment]
Closing all API related issues to implement them as needed for ``ptl`` with spinoff API development rather than leaving these open.
