### ISSUE TITLE
Pootle user documentation as part of Pootle

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2330]
Depends on:
- [x] #2455 Setup Sphinx docs structure
- [x] #2456 Migrate from wiki docs to Sphinx docs
- [x] #2457 Publish Pootle docs at readthedocs
- [x] #2460 Redirect from old wiki docs to Sphinx docs
- [x] #2462 Replace wiki references in the code by new docs

Migrate user documentation from the wiki to Sphinx and away from the custom webpages we have in Pootle.

Current Problem:
- There is no documentation relationship between the Pootle release and online docs
- The docs are not part of a Pootle install thus requiring outside access for Pootle users who might be working local.
- The docs can't be made to match the local look and feel.

Solution:
- Move the current wiki docs to Sphinx
- Integrate the output from Sphinx into the server
- Publish docs on readthedocs
- Make this all part of the automated build process.
