### ISSUE TITLE
Deploy Pootle at Mozilla

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2340]
Depends on:
* [ ] #2280 Verbatim needs to use an indexing engine
* [x] #2341 Examine the possible inclusion of mozilla-pootle-extras
* [x] #2342 Decide on Git deployment strategy for Verbatim
* [x] #2441 Do test upgrade of Mozilla server

Deployment of Pootle at Mozilla

**Comment by dwaynebailey** [comment]
Closing this.  We'll track Verbatim upgrade on its own milestone related to deployment on core.
