### ISSUE TITLE
Project description implementation issues

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2376]
Depends on:
- [x] #2192 Align project and language description's look with overview pages
- [x] #2193 Cancel and save buttons in description update are confusing
- [x] #2194 Use markup filters for description info
- [x] #2195 Translation project description hides inherited descriptions
- [x] #2198 With no description there is no logical place for the edit icon
- [x] #2199 Hide/Show description is too far away from description
- [x] #2382 Some includes are not compatible with Django 1.2
- [x] #2414 Hide language and project descriptions in translation projects
- [x] #2423 Edit/Cancel icons for project descriptions are not close to the actual edit widget
- [x] #2424 Opening project descriptions causes screen to jump

This tracks any bugs or issues that came out of the project/language/translation project description pages.
