### ISSUE TITLE
All text input allows markdown/rst/etc as configured

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2377]
Depends on:
* [x] #2194 Use markup filters for description info
* [ ] #2378 Use markup filters for news input
* [x] #2380 Setting MARKUP_FILTER with markup module missing causes traceback
* [ ] #2381 Admin->General project description should accept any markup

With the introduction of legal pages we added the ability to specify how people could enter rich data.

This now include: markdown, restructured text and html.

This tracker is about finding all the places that should be converted to use that feature.  This ensures that a user has a consistent site-wise experience of the feature.

**Comment by dwaynebailey** [comment]
Lets revisit this if its an issue on ``core``.
