### ISSUE TITLE
Legal pages implementation issues

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2379]
Depends on:
* [x] #2328 Long delay in availability of legal pages when your first create them
* [x] #2334 Legal page display "Valid markup: %s"
* [x] #2335 Legal pages: url vs local content distinction is not clear
* [x] #2336 Legal pages allow XSS in the description
* [x] #2337 Add some other potentially useful legal page titles to allow easy localisation
* [x] #2338 Standard styling for user contributed HTML
* [x] #2339 Require acceptance of Terms of Use or similar legal pages
* [x] #2380 Setting MARKUP_FILTER with markup module missing causes traceback
* [x] #2777 Replace get_legalpages template tag
