### ISSUE TITLE
News publication implementation issues

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2384]
Depends on:
* [ ] #2378 Use markup filters for news input
* [ ] #2385 No error message when you try to post a blank message
* [x] #2386 News can be published where you don't have permissions
* [x] #2387 News targets: languages & projects are not limited by publishing location
* [ ] #2388 News publication to All now published to each language individually
* [ ] #2389 News should show the gravatar of the writer
* [ ] #2390 News publishing dialog is confusing
* [ ] #2391 Sending a message to the whole server is impossible
* [ ] #2392 Ability to delete a message
* [ ] #2393 The news tab should fold into the overview tab
* [x] #2398 Publish News has some untranslatable strings
* [x] #2568 News emails expose contributors email addresses
* [x] #2569 News post to language project sends to everyone

These are issues identified with the review of bug #2169.

They are not all specifically related to the new implementation but it is simpler to track them here as one.

**Comment by dwaynebailey** [comment]
News will need a whole revisit on ``core``, so closing this.
