### ISSUE TITLE
Timeline implementation issues

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2404]
Depends on:
* [x] #2354 Clicking on unit suggestions appends text instead of overwriting
* [x] #2355 Clicking on timeline should copy the target
* [ ] #2357 Comment is lost if you submit unit instead of comment
* [x] #2361 No indication of timeline date and time of submission
* [ ] #2401 Accepting suggestion does not change unit state
* [x] #2402 Change fuzzy to needs work
* [x] #2405 Last translator gravatar is too far from translation
* [x] #2406 Accepting suggestions assigns correct translation credit but we need review credit
* [x] #2407 Missing gravatar is ugly
* [ ] #2408 Impossible to delete comment from unit

All bugs or issues identified after the timeline implementation.

This is a catchall bug for anything that was changed for the timeline implementation.

**Comment by dwaynebailey** [comment]
There feature is there.  Lets deal with bugs on their own, thus closing the tracker.
