### ISSUE TITLE
Issues related to overview actions implementation

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2504]
Depends on:
* [x] #1335 [VCS] Enable commit for a complete directory / language / project
* [x] #2506 Overview actions Delete should display an alert before proceeding
* [x] #2507 Overview actions that take a long time have no busy indicator
* [x] #2511 Avoid deleting a translation project's directory
* [x] #2512 Alerts cover the error message
* [x] #2513 No link to export as XLIFF
* [x] #2515 Incorrect message after deleting a directory
* [x] #2562 No way to access online translation when file is 100% translated

This bug tracks any issues identified in the implementation of bug #2415

**Comment by dwaynebailey** [comment]
All tasked closed and we're not tracking this anyway.  So closing
