### ISSUE TITLE
Expand Pootle manage.py API commands

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2532]
Depends on:
* [x] #1845 Optimize update_stores command to skip files which were not modified
* [x] #2533 ./manage.py get_last_id — print out latest translation id in the database
* [x] #2534 ./manage.py sync_stores --modified-since-id=NNNN
* [x] #2535 ./manage.py list_projects — dump all registered project names
* [x] #2536 ./manage.py list_languages" — dump all registered language names
* [ ] #2563 Factor out merging logic
* [ ] #2564 Reuse merging logic for update_stores

**Comment by dwaynebailey** [comment]
Closing it as its not a current goal.
