### ISSUE TITLE
Remove upstream code from Pootle

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2580]
Depends on:
- [x] #2517 [DeprecationWarning] Replace function-based generic views
- [x] #2579 Remove django-registration from code and use upstream
- [x] #2581 Investigate the removal of upstream code from Pootle
- [x] #2585 Use upstream version of djblets
