### ISSUE TITLE
Pootle 2.5.1 release

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2586]
Depends on:
- [x] #1988 Add commit status flag on each PO
- [ ] #2264 Ability to take a language, project or translation project offline
- [x] #2438 Design Pootle URLs
- [ ] #2451 No direct URL for displaying expanded checks
- [x] #2580 [TRACKER] Remove upstream code from Pootle
- [x] #2588 Exported PO files use only the firstname field
- [x] #2589 Expose keyboard shortcuts to users
- [x] #2595 User suggestions should contain a date
- [x] #2597 Post login redirect does not take you back to where translating
- [x] #2618 update_store reports INFO message when no --modified-since is supplied
- [x] #2619 Sending news on a project shows all site languages not just those enabled for the project
- [x] #2623 Validate that all links are clickable
- [ ] #2631 User can review own suggestions
- [ ] #2649 Markdown can't parse URLs like https://wiki.mozilla.org/L10n:Teams:shn
- [x] #2752 Use collectstatic --noinput --clear when dropping support for Django 1.3.x
- [x] #2841 Provide upgrading functionality through a single command
- [x] #3058 Change development DB from SQLite to another one
- [x] #3078 Tagging: Make sure that install/upgrade works fine after taggit was added

A gathering place for all bugs that we'd like to fix for a Pootle 2.5.1 release
