### ISSUE TITLE
Rework migration process

### ISSUE THREAD

**Issue by julen** [translate/pootle#2771]
Depends on:
- [x] #2652 Remove the ability to upgrade the DB from the web UI
- [x] #2772 Ensure updatedb works after removing upgrades from the web
- [x] #2773 Setup schema and data migrations using South commands

Tracker bug filed based on bug #2652.

This should at least consist of the following tasks:
- Removing the ability to trigger upgrades from the web UI
- Ensuring `updatedb` still works, and providing an informational messages to users pointing them to the new migration command.
- Setup schema/data migrations using South management commands.
