### ISSUE TITLE
Revamped static pages

### ISSUE THREAD

**Issue by julen** [translate/pootle#2825]
Depends on:
* [x] #2379 Legal pages implementation issues
* [x] #2826 Rename legalpages to staticpages
* [x] #2827 Move common static page functionality into an abstract page model
* [x] #2828 Adapt existing models using markup filters to store the result in the cache
* [x] #2829 Implement internal page linking
* [x] #2830 Implement versioning for static pages
* [x] #2831 Track who accepted a ToS and when
* [x] #2865 Adapt admin UI bits for the new static pages
* [x] #2866 Add static page model
* [x] #2910 Handle legal page agreements via popups
* [x] #2911 Allow administrators to see inactive pages
* [x] #2922 Don't update modified_on timestamp if no actual content has been modified

Tracker bug for revamped static pages.

**Comment by dwaynebailey** [comment]
@julen I guess we can safely close this tracker?
