### ISSUE TITLE
Add basic API to Pootle

### ISSUE THREAD

**Issue by unho** [translate/pootle#2874]
Depends on:
* [x] #2344 Setup API framework
* [ ] #2873 Expand the API specs
* [x] #2951 API: Add initial resource and docs for Project
* [x] #2952 API: Add initial resource and docs for Language
* [x] #2953 API: Add initial resource and docs for TranslationProject
* [x] #2954 API: Add initial resource and docs for Store
* [x] #2955 API: Add initial resource and docs for Unit
* [x] #2956 API: Add initial resource and docs for Suggestion
* [x] #2957 API: Show statistics in nested /statistics/
* [x] #2958 API: Restrict access to make users "see" only its own User resource
* [x] #2959 API: Add initial resource and docs for User
* [x] #2960 API: Add statistics to UserResource
* [x] #2982 API: Add basic filtering on several UnitResource fields

This includes:

* Add a basic API that follows the API specs
* Add documentation for the new basic API

This depends on expanding the API specs http://bugs.locamotion.org/show_bug.cgi?id=2873

**Comment by dwaynebailey** [comment]
Closing this.  We can open a new tracker when we get back to looking at API related stuff.
