### ISSUE TITLE
DB initialization issues

### ISSUE THREAD

**Issue by julen** [translate/pootle#2887]
Depends on:
- [x] #2884 Migration: App 'legalpages'
- [x] #2885 DoesNotExist: User matching query does not exist.
- [x] #2886 django.db.utils.IntegrityError: pootle_app_project.description_html may not be NULL

Since we moved over South, there seem to be some issues related to how the DB initialization is done in the `initdb` command. This is the tracker bug for such issues.
