### ISSUE TITLE
Get goals back in core

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3301]
Document with specs: https://docs.google.com/document/d/16g_ustDX2Pxm8yasqIw_kXXi2g1oU25iOnjOBCYcYWc

Already addressed on previous PRs and merged:

- [x] #3521 Add initial infrastructure to create VirtualFolders
- [x] #3522 Put in place engine to filter VirtualFolders using their filter and locations
- [x] #3613 Sort units by vfolder priority on editor
- [x] #3614 Translate links in TP overview transparently set priority sorting if a vfolder applies
- [x] #3632 Display unit priority on editor
- [x] #3524 Filter the units in the editor using a VirtualFolder
- [x] #3556 List matching vfolders above the stats table
- [x] #3643 Accept path filters on the JSON
- [x] #3525 List and select VirtualFolders on the editor navbar dropdown
- [x] #3652 Priority sorting shouldn't always be available
- [x] #3637 Overview table lists all VFolders if you are an admin
- [x] #3635 Relate newly added units with existing vfolders

**Comment by unho** [comment]
@iafan We want to start working on this, since it is a key feature for one of our customers. Is it possible for you to discuss the questions/doubts in the Google doc with the specification (linked in this issue description)?

**Comment by unho** [comment]
Closing this. Tasks that still have to be completed had been moved to #3725.
