### ISSUE TITLE
Documentation fixes for 2.7.0 post-core

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3307]
Docs will need to be reviewed and updated based on what we landed, the EN-specific stuff that was removed etc and all the things we updated in the docs since the fork. This is standalone work so on hold until we get further into the code migration.

* Document recovery
  * [x] #3480 Pick installation/upgrade docs from stable/2.6.0
  * [x] #3490 Pick the changes done in releasing docs in stable/2.6.0
  * [x] #3491 Pick the release notes from stable/2.6.0
* Cleanups, fixes, reviews
  * [x] #3492 The now outdated evernote_changelog.rst needs to be dropped
  * [x] #3142 Merge Pootle changelog into release notes
  * [x] #3512 Merge upstream_differences.rst into release notes
  * [x] #3514 Review and adjust installation instructions
  * [x] #3493 Document the upgrade from 2.x to 2.7.0
* Undocumented features
  * [x] #3495 Document the legal agreement feature
  * [x] #3473 Add docs on how to setup background jobs
  * [x] #3351 Mention the hard-dependency on Redis
  * [x] #3510 Document ElasticSearch TM functionality
  * [x] #3511 Review documentation for new cofiguration settings
* Improvements
  * [x] #3215 Document simple database setup commands for our supported databases

**Comment by unho** [comment]
Important reminder: pick new changes done to installation and upgrade docs.

**Comment by unho** [comment]
Related issue https://github.com/translate/pootle/issues/3473

**Comment by dwaynebailey** [comment]
All our main docs are done for 2.7.0
