### ISSUE TITLE
Core: Reimplement allauth

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3343]
Core uses the old Pootle authentication while 2.6 moved to allauth to provide a more modular approach to authentication.  The divergent authentication methods is a big blocker to merging the code.

The approach will be to land allauth on core as follow:

1. [x] Translate integrates allauth in core, using a feature branch for doing so (#3447 & #3468)
2. [x] Translate implements the workflow with Evernote's help (#3517)
3. [x] Evernote implements the allauth Evernote backend (#3515)
4. [ ] Evernote addresses styling UI issues (#3518)
5. [x] Verify previously-existing email when using a social account (#3728)
6. [x] Sync-up email addresses when editing users (#3737)

Also depends on:
* [x] Must be able to disable user sign ups (#3449)
* [x] CSRF cookie might be missing in private browsing sessions (#3774)

**Comment by dwaynebailey** [comment]
Some observations of things that maybe need clarification on the mockups vs current screens/workflow

- 'Remember me' is missing from the mockup signups (do we still want that? My guess is yes)
- Settings->'Link with Evernote' (this needs to go but I assume kept with EN backend)

**Comment by iafan** [comment]
We can add the 'remember me' option (and have it checked by default).

As for sign up not asking for the user's full name, I think it's ok. I'd try to make sign up flow as simple/fast as possible, and then provide a way for the user to discover the convenient form to fill in their profile (and probably add some score when one fills in their profile).

**Comment by ta2-1** [comment]
I've created #3515 where we adjust Evernote backend to allauth branch.
the UI work can be left for the future.

**Comment by ta2-1** [comment]
The question we haven't discussed: how do we connect different social accounts?

**Comment by julen** [comment]
> The question we haven't discussed: how do we connect different social accounts?

This is a question to be answered in #3517.

**Comment by julen** [comment]
FTR: I've split the separate concerns described here into more manageable subtasks.
