### ISSUE TITLE
Redis is a hard-dependency for RQ and for cache

### ISSUE THREAD

**Issue by julen** [translate/pootle#3351]
Redis now being a hard-dependency (job queue, revision counter also in the near future), we need to update docs, depchecks and code assumptions accordingly.

Developers also agreed that it makes more sense to use it more effectively, therefore:

1. It'll be enforced as The caching backend. People won't need to have both Redis + memcached, but the former will be enough.
2. Developers will be able to use lower-level Redis capabilities when it's required/justified, be it for improved footprint or performance reasons. For any standard use of the cache, general Django APIs are enough.

* [x] #3585 Setup default stats cache
* [x] #3590 Move from django-redis-cache to django-redis
* [x] #3591 Drop memcached as preferred cache and change all docs accordingly
* [x] Reflect all of this in the docs.

**Comment by dwaynebailey** [comment]
This also needs updates in:

1. depcheck
2. dashboard

Essentially ``grep memcache``

**Comment by dwaynebailey** [comment]
@julen busy looking at this.  Was there any reason to choose [django-redis-cache](https://github.com/sebleier/django-redis-cache) over [django-redis](https://github.com/niwibe/django-redis)?

**Comment by julen** [comment]
Nothing specific that I'm aware of, probably the first that we found for the basic caching needs at the time. Anything else you could think of @ta2-1?

**Comment by julen** [comment]
But also check my comment on https://github.com/translate/pootle/issues/3585#issuecomment-73847522 if you haven't do so yet.
