### ISSUE TITLE
Be Django 1.7 compatible

### ISSUE THREAD

**Issue by julen** [translate/pootle#3354]
We must ensure we're Django 1.7 compatible, let's track that here.

The blockers are:
* [x] Move to built-in Django migrations (#3355)
* [x] Set sane defaults for `SESSION_CACHE_ALIAS` (#3356)
* [x] Rename `Submission` model's `check` field (#3462)
* [x] Pages pending user agreement cannot be retrieved (#3506)

There are other cleanups that can be done and niceties introduced in Django 1.7 but those are out of the scope of this issue.

Resources:
* [Django 1.7 release notes](https://docs.djangoproject.com/en/dev/releases/1.7/)
* [Django deprecation timeline](https://docs.djangoproject.com/en/dev/internals/deprecation/)

**Comment by jleclanche** [comment]
@julen With your most recent release, this is done, yes?

**Comment by julen** [comment]
Hold on, nothing has been pushed yet.

**Comment by unho** [comment]
@julen @jleclanche  #3355 is marked as done, but the issue is still open. The same for #3462.
