### ISSUE TITLE
Migration of existing translations to core

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3357]
The plan is to continue to land translations on stable/2.6.0.

Once core is the main target we will need to do the follow:

* [x] Pull and land all existing translation work on core
* [x] Review core for localisability
* [x] Update translations and republish

**Comment by unho** [comment]
@dwaynebailey Is PR #3571 a fix for the second item in this issue?

**Comment by unho** [comment]
@dwaynebailey Is this issue solved?

**Comment by unho** [comment]
@dwaynebailey Translations need to be updated again because of 16c0f1c1.

**Comment by dwaynebailey** [comment]
Marking this as done.  There are some l10n issues that landed in 89ab0d35cf4a792ff4eef81e7b094b2f0d798f7b and 2b02e610db35afbf7d38e31738d5c6458adc88bd but we'll handle those as they arrive.  The general pull and update has happened twice now.
