### ISSUE TITLE
Core: drop MySQL dependence on MyISAM

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3363]
Core depends on MyISAM at the moment because of low level features used for changeid tracking.  We need to migrate that to a more general approach that works on InnoDB and other supported DB engines.

* [x] Make resources list work in all DB backends (#3539)
* [x] Switch revision counter to Redis (#3364)
* [ ] Ensure tests run on InnoDB (#3777)

**Comment by dwaynebailey** [comment]
InnoDB still fails on with InnoDB in tests https://travis-ci.org/dwaynebailey/pootle/jobs/50399443
