### ISSUE TITLE
Add docs for the new EN features that are not present on 2.5.1.1

### ISSUE THREAD

**Issue by unho** [translate/pootle#3474]
Like the new local TM and such.

* [ ] https://github.com/translate/pootle/issues/3473 Add docs on how to setup background jobs
* [ ] https://github.com/translate/pootle/issues/3351 Mention the hard-dependency on Redis
* [ ] #3500 document flush_cache command

**Comment by dwaynebailey** [comment]
Can we just track this as a tasklist possibly with subbugs on #3307

**Comment by unho** [comment]
@dwaynebailey I think both this issue and #3307 should be trackers. And this issue should be included on #3307 when it becomes a tracker.

**Comment by dwaynebailey** [comment]
Merged into #3307
