### ISSUE TITLE
Finish and improve virtual folders implementation

### ISSUE THREAD

**Issue by unho** [translate/pootle#3725]
Document with specs: https://docs.google.com/document/d/16g_ustDX2Pxm8yasqIw_kXXi2g1oU25iOnjOBCYcYWc

This is the continuation for #3301.

- [ ] #3721 Improve performance of project resources creation
- [ ] #3720 Cache stats for all vfolders
- [ ] #3714 Files table sorting breaks vfolders table sorting
- [ ] #3715 Always display completely translated vfolders with failing checks
- [ ] #3716 Allow to edit units with failing checks for not browsable vfolders
- [ ] #3690 Decouple vfolders
- [ ] #3641 Add tests for virtual folders
- [ ] #3636 List and select VFolders on all overview navbar dropdowns
- [ ] #3523 Drill down in a VirtualFolder within TP overview
- [ ] #3638 Drill down in a VirtualFolder in any overview
- [ ] #3534 Alter VirtualFolder.save() to to append `-virtual` to the name if necessary
- [ ] #3619 Translate links on all overviews transparently set priority sorting if a vfolder applies
- [ ] #3634 Add management command to delete vfolders
- [ ] Add admin section to manage VirtualFolders
- [ ] Be able to filter units using a VirtualFolder (marked with hashtags on the store)
