### ISSUE TITLE
Remove dependency on Backbone.js

### ISSUE THREAD

**Issue by julen** [translate/pootle#4662]
Some client-side code is depending on [Backbone](http://backbonejs.org/) for models, collections, views and (underscore) templates, however all of this becomes irrelevant now that new UI code is written in React.

While these two can live together (the admin app serves as an example), it's a dependency we can get rid of because React already takes care of:
* Views. This is done via reusable components and with no need to manage the DOM, hence BB views and templates become unnecessary.
* Data. Well, truth to be said React has nothing to do with data management and forces nothing on what you pass to it, nevertheless the benefit of models/collections in BB is when using them along with views: with React plain old JS objects play better and are lighter, and can then be used with [single-atom state containers](http://redux.js.org/), which we have in place to some extent.

Besides that, it's way easier to focus on one approach rather than being distracted with multiple ways of doing things.

Action items:
* [ ] Remove BB from the user profile view
* [ ] Remove BB from admin pages (user, language, project admins share a big chunk of code)
* [ ] Remove BB from the editor (unit model/collection)
* [ ] Remove BB from the message helper
* [ ] Remove BB view from the user dropdown
