### ISSUE TITLE
Implement Due Dates functionality

### ISSUE THREAD

**Issue by julen** [translate/pootle#4799]
(Check the [original spec](https://docs.google.com/document/d/1XqhEtDKVJsN-mvxGNslPrIa4w3LeTWolLhFlzt8VTN0/edit?ts=56fb0436#) for further background information).

## Goals and problems being solved
1. At any point in time, give translators a clear plan what to work on next, along with deadlines.
2. Spare project managers from communicating deadlines over email, from sending repetitive reminders and digests.

### Action items

* [ ] Administration widget in browsing pages
* [ ] Implement dashboard in browsing pages
* [ ] Implement notification emails
* [ ] Admin dashboard
