### ISSUE TITLE
RTL issues

### ISSUE THREAD

**Issue by unho** [translate/pootle#4925]
Summary of RTL issues:
- [ ] Numbers in columns are left aligned, is that right? Or is it just my LTR head
- [ ] This alignment causes some issues are they don't make it easy to see what is which column in the browse table
- [x] Expanded navbar view: the icon for the user appears far left so you actually get the page scrolled left just for the icon
- [x] I'm concerned the icon, name order in the collapsed navbar is not correct
- [ ] Score is N+ in LTR its +N. Does that work in RTL? Should '+%d' be localised?
- [ ] LTR project titles elipsised have elipsis on left instead of right
- [ ] Dropdown should drop Left in RTL otherwise the dropdown renders offscreen #4847 also rights selector widgets fills LTR

Followup for #4848 including missing bits from #4896.

Next message picked from https://github.com/translate/pootle/pull/4896#issuecomment-233564867

> > - Numbers in columns are left aligned, is that right? Or is it just my LTR head
> > 
> > Maybe you are correct. 2.5 was displaying them right-aligned.
> 
> This is just the opposite of what we have for LTR.
> 
> This is LTR:
> ![ltr](https://cloud.githubusercontent.com/assets/939880/16868097/0b241676-4a76-11e6-9e9f-4905fc07fc29.png)
> 
> And this is RTL:
> ![rtl](https://cloud.githubusercontent.com/assets/939880/16868098/0b2ac70a-4a76-11e6-96b1-9e36c47d043b.png)
> 
> > > - This alignment causes some issues are they don't make it easy to see what is which column in the browse table
> > 
> > If we're going to correct the numbers, then it's safe to make them all right-aligned.
> > 
> > > - Expanded navbar view: the icon for the user appears far left so you actually get the page scrolled left just for the icon
> > 
> > Thanks for the notice! I tried but didn't know how to fix it. :(
> 
> I didn't saw this. Can you please share a screenshot?
> 
> Perhaps related, I fixed the separation between top contributors when details are collapsed.
> 
> > > - I'm concerned the icon, name order in the collapsed navbar is not correct
> > 
> > Seems like the one above..
> 
> Not sure what are you talking about either.
> 
> > > - Score is N+ in LTR its +N. Does that work in RTL? Should '+%d' be localised?
> > 
> > I would say adding:
> > 
> > ```
> > html[dir="rtl"] .path-summary-more .top-scorers-table tr td.number:last-child {dir="rtl"}
> > ```
> > 
> > Now there are these:
> > 
> > ![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16877541/517ef3f8-4ab1-11e6-9bc3-53a3fd904b22.png)
> > 
> > The arrows should be mirrored/flipped. Both of them have the same css and that's beyond my knowledge :smile:
> > This is for both the simplified and detailed one.
> > 
> > The last thing (for now?) is that the detailed statistics page need to be RTL (main html doesn't have `dir="rtl"` attrib set.

**Comment by unho** [comment]
@SafaAlfulaij @dwaynebailey I will need some clarification on some of the issues above.

**Comment by dwaynebailey** [comment]
@unho I'm not sure which are the issues, there is just too much info in the OP

**Comment by unho** [comment]
@dwaynebailey Ok, will try to break down the not clear items:

> - Numbers in columns are left aligned, is that right? Or is it just my LTR head
> - This alignment causes some issues are they don't make it easy to see what is which column in the browse table

What RTL gives is the opposite of LTR, despite perhaps we need to adjust some paddings or such. But AFAICT you are talking about altering the alignment for both?

> - Expanded navbar view: the icon for the user appears far left so you actually get the page scrolled left just for the icon

I have no idea what you are talking about. Screenshot and/or more details please.

> - I'm concerned the icon, name order in the collapsed navbar is not correct

Details and/or screenshot too, please.

> - Score is N+ in LTR its +N. Does that work in RTL? Should '+%d' be localised?

Again please details and/or screenshot.

**Comment by SafaAlfulaij** [comment]
> Expanded navbar view: the icon for the user appears far left so you actually get the page scrolled left just for the icon

And (Not the cursor, but the numbers at the left (81+) ):
> Score is N+ in LTR its +N. Does that work in RTL? Should '+%d' be localised?


![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16996030/0dbf0b2a-4eb8-11e6-931f-cef1503391df.png)

> I'm concerned the icon, name order in the collapsed navbar is not correct

(Overlaping icon with text in the row where (+) button is on the left)

![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16996078/49f0522a-4eb8-11e6-86bb-3076ecfa9b80.png)

**Comment by SafaAlfulaij** [comment]
For (Not tested!):
> the detailed statistics page need to be RTL (main html doesn't have dir="rtl" attrib set.)

```
diff --git a/pootle/templates/admin/detailed_reports.html b/pootle/templates/admin/detailed_reports.html
index 3e72e51..c20d412 100644
--- a/pootle/templates/admin/detailed_reports.html
+++ b/pootle/templates/admin/detailed_reports.html
@@ -1,6 +1,7 @@
-{% load i18n common_tags %}
+{% load i18n locale common_tags %}
+{% get_current_language as LANGUAGE_CODE %}
 <!DOCTYPE html>
-<html>
+<html lang="{{ LANGUAGE_CODE }}" dir="{% locale_dir %}">
 <head>
   <meta charset="utf-8">
   <title>{% blocktrans with object.display_name as user %}Report for {{ user }}, {% endblocktrans %}{% format_date_range start end " &ndash; " %} | {{ settings.POOTLE_TITLE }}</title>
```

_Is "lang" important?_

and (Not tested!):

> The arrows should be mirrored/flipped. Both of them have the same css and that's beyond my knowledge :smile:


```
diff --git a/pootle/templates/admin/reports/header.html b/pootle/templates/admin/reports/header.html
index 56fe9b6..182049d 100644
--- a/pootle/templates/admin/reports/header.html
+++ b/pootle/templates/admin/reports/header.html
@@ -1,4 +1,4 @@
-{% load i18n %}
+{% load i18n locale %}
 <table id="reports-header">
   <tr>
     <td id="reports-form">
@@ -8,11 +8,13 @@
       <div class="dates">
         <ul>
           <li>
-            <a class="js-month js-previous" href="#"><span class="arrow">&larr;</span> {% trans "Previous month" %}</a>
+            <a class="js-month js-previous" href="#"><span class="arrow">
+            {% if locale_dir != "rtl" %}&larr;{% else %}&rarr;{% endif %}</span> {% trans "Previous month" %}</a>
           </li>
           <li class="selected"></li>
           <li>
-             <a class="js-month js-next" href="#">{% trans "Next month" %} <span class="arrow">&rarr;</span></a>
+             <a class="js-month js-next" href="#">{% trans "Next month" %} <span class="arrow">
+             {% if locale_dir != "rtl" %}&rarr;{% else %}&larr;{% endif %}</span></a>
           </li>
         </ul>
       </div>
```

**Comment by dwaynebailey** [comment]
LTR project titles elipsised have elipsis on left instead of right:
![](https://files.gitter.im/translate/pootle/RHjg/Screen-Shot-2016-07-21-at-14.40.20.png)

**Comment by dwaynebailey** [comment]
Dropdown should drop Left in RTL otherwise the dropdown renders offscreen:
![screen shot 2016-07-21 at 14 40 04](https://cloud.githubusercontent.com/assets/647438/17025105/5c04bc4a-4f52-11e6-91a0-5961f8578c51.png)

**Comment by SafaAlfulaij** [comment]
@dwaynebailey For the dropdown, see #4847

**Comment by SafaAlfulaij** [comment]
> Dropdown should drop Left in RTL otherwise the dropdown renders offscreen:

Project names direction should be detected and set (Server-side?)

**Comment by SafaAlfulaij** [comment]
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/16877181/a6abdb2c-4aaf-11e6-965f-f3549ce730b0.png)

This isn't fixed. To fix it, https://github.com/translate/pootle/blob/master/pootle/static/css/editor.css#L1383 should be `left: auto;`

**Comment by SafaAlfulaij** [comment]
**This:**

```css
html[dir="rtl"] #translate-filters .breadcrumb
{
    margin-left: auto;
    margin-right: 2em;
}
```
Here: https://github.com/translate/pootle/blob/master/pootle/static/css/actions.css#L195

**This:**

```css
html[dir="rtl"] .path-summary-more .top-scorers-table tr td.number:first-child
{
    text-align: right;
}
```
Here: https://github.com/translate/pootle/blob/master/pootle/static/css/scores.css#L139

**For:**
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17028651/ebcaf5d8-4f70-11e6-8e9d-c63f394bbe91.png)

`dir="rtl"` should be added to both the username and password in https://github.com/translate/pootle/blob/master/pootle/static/js/auth/components/SignInForm.js#L93:L108

**For:**
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17028705/1d99c1ca-4f71-11e6-9c60-9c32f7e36650.png)

`transform: scaleX(-1);` should be added for `icon-folder-parent`. Got it from: http://stackoverflow.com/questions/5768998/how-to-flip-background-image-using-css


**For:**
>  Expanded navbar view: the icon for the user appears far left so you actually get the page scrolled left just for the icon
>  I'm concerned the icon, name order in the collapsed navbar is not correct

Solved by:
- Adding `right: 0;` to `.top-scorer img.avatar`
- Removing `display: block;` from `.path-summary-more .top-scorer .user-name`

**Comment by SafaAlfulaij** [comment]
New issues (Hopefully last):
- `html[dir="rtl"] .hd h2` rule should be removed.
- `html[dir="rtl"] .path-summary-more .summary-3-col` rule should be removed
- `#top-scorers .user .gravatar, #top-scorers .user .properties` : `float=right` and `text-align=right`

- Direction of URLs in static pages view is RTL, which should be LTR. Couldn't find a CSS selector to change. _Priority: Low_
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/22373783/6df50750-e4b4-11e6-81da-644f9043cb5e.png)

- Some overlappings in the string editor page, for the checks. Both the RTL and LTR version are affected.
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/22373904/e78ccf6c-e4b4-11e6-9e7a-73e5749bab4a.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/22373903/e78b91e2-e4b4-11e6-8a0f-c59fc3a00810.png)

### Old existing issue:

> For:
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17028705/1d99c1ca-4f71-11e6-9c60-9c32f7e36650.png)

>transform: scaleX(-1); should be added for icon-folder-parent. Got it from: http://stackoverflow.com/questions/5768998/how-to-flip-background-image-using-css

**Comment by phlax** [comment]
thanks @SafaAlfulaij ill go through shortly and add a PR

**Comment by phlax** [comment]
hi @SafaAlfulaij ive addressed most of the new issues you posted in #5913 

in relation to the last issue - the "old existing issue" - im not sure what is not correct

**Comment by SafaAlfulaij** [comment]
Thanks @phlax !
The arrow is pointing to the left, while it should point to the right. That `transform` command should fix it.

**Comment by phlax** [comment]
> The arrow is pointing to the left

ah, k got it now

**Comment by unho** [comment]
Closed in favor of several new smaller and more specific RTL issues.
