### ISSUE TITLE
[Tracker] Reduce impact of robots on Pootle performance

### ISSUE THREAD

**Issue by unho** [translate/pootle#4977]
We have found that on some deployments robots are having a big impact performance on some views that are expensive and that we haven't improved performance on because they are very rarely visited by human users. Among these are the user's profiles, the user's statistics and the user's detailed statistics.

In order to improve performance the following are suggested:
- [x] #4995 Make user's statistics and the user's detailed statistics only accessible for logged in users, so robots don't even know about them
- [ ] Display latest activity on user's profile only for logged in users since this is expensive query and might expose activity on private projects
- [ ] Optimize those three views
- [ ] Prevent access to detailed statistics to time frames outside of the data held by Pootle, since we shouldn't display links in user's stats to activity in April 1973 or June 3104 because Pootle surely doesn't have records for those.

**Comment by dwaynebailey** [comment]
Also: prevent access to detailed statistics in the future or earlier then available data within Pootle.

**Comment by unho** [comment]
Picked. Thanks.

**Comment by julen** [comment]
Hearing robots made me recall of an old issue we had on file at evernote/pootle#24. I migrated that over to #4979. Addressing that one should be easy and it probably brings a noticeable improvement in a cheap way as it would avoid legitimate bots from crawling a server.

**Comment by unho** [comment]
These views, or the unperformant parts of them, have been removed. So closing.
