### ISSUE TITLE
Pootle 2.0 release

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#672]
Depends on:
- [x] #652 Pick up UI strings from OLPC
- [x] #673 Burry jToolkit for Pootle 1.3
- [x] #674 Ensure LDAP functionality is working for Pootle 1.3
- [x] #675 TRACKER: Review all user interface issues for Pootle 1.3
- [x] #679 AttributeError: 'DummyTranslation' object has no attribute 'languagecode'
- [x] #686 Error when viewing PO files
- [x] #687 Error when viewing suggestions
- [x] #688 Traceback when changing personal options
- [x] #689 Traceback in old add user interface
- [x] #691 pootle_app needs to be in PYTHONPATH
- [x] #766 Unit tests need to be updated to work with the new Django server
- [x] #794 PO files created at project Root instead of corresponding POT directories under GNU style projects
- [x] #815 Cannot set permissions for users in a project
- [x] #840 Unable to add permissions for users
- [x] #848 global name 'spellcheck' is not defined
- [x] #861 Accepting and rejecting suggestions doesn't work through the ajax interface
- [x] #862 Alternative source language not working with the current trunk
- [x] #870 Cannot make suggestions
- [x] #905 "Administrate" link is not displayed
- [x] #914 Setting UI language in options has no effect
- [x] #924 User rights not applied properly
- [x] #925 Quality checks are missing
- [x] #956 l10n of UI not working
- [x] #957 l10n of language names not working
- [x] #1036 Combined search doesn't work
- [x] #1038 Unexpected behaviour with suggestions
- [x] #1149 Can't suggest already suggested and reviewed strings
- [x] #1150 Can't suggest on units with plural forms
- [x] #1151 Suggestion's information is not updated after a review
- [x] translate/translate#1155 Review the use of the "print" statement
- [x] #1157 User account doesn't display quick links
- [x] #1164 Rejecting suggestions fails
- [x] #1176 Reviews column is not used in the Top Contributors table
- [x] #1185 Export to ZIP not displayed

_Version: 1.2.0_

This is a tracking / blocking bug for Pootle 1.3.

Pootle 1.3 should be on feature parity with Pootle 1.2.1 after migrating to Django. The new interface needs to be finished. Branding will probably receive attention to some (undetermined) extent, visual bugs should be fixed, and documentation should be up to date to allow testers, packagers, and users of Pootle 1.3 to have a comparable experience from an installation viewpoint.
