### ISSUE TITLE
Review all user interface issues for Pootle 1.3

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#675]
Depends on:
- [x] #677 Drop double-click based edit UI
- [x] #680 Register should be a link, not a button
- [x] #681 Ugly horizontal scrollbar appears once logged in
- [x] #690 Admin login doesn't work on fancy login
- [x] #710 Current translation unit is always displayed on top
- [x] #738 Welcome text too large
- [x] #739 The translate table doesn't have a fixed layout
- [x] #740 Review RTL functionality throughout Pootle
- [x] #770 Please define background color in CSS
- [x] #811 "Log in" link should be labeled "Log in/Register"
- [x] #814 Update favicon for Pootle 1.3
- [x] #837 Login form still showing up in the footer
- [x] #838 horizontal scroll bar flashes when clicking on certain links
- [x] #865 Language dropdown not sorted according to the locale
- [x] #866 Search box not associated with navigation bar
- [x] #886 No way of getting to the activate page except for automatic redirect
- [x] #958 Fix styling of related (terminology/tm) entries
- [x] #959 No message saying that we are reviewing a check
- [x] #1039 Review English source strings for Pootle 1.3

This is a testing bug or possibly a blocking / tracking bug for everything related to user interface issues for the upcoming Pootle 1.3.

The new look from the Mozootle branch has been merged before the Django migration. Some parts are said to be not complete, some functionality needs to be brought back (terminology and TM come to mind), branding will need attention, and RTL is broken since the merge of the new look.

Branding suggestions as part of the rebranding of the whole Translate project (website, Virtaal, Toolkit, Pootle) might make it in for 1.3.
